"""Unit and integration tests for real-time GDT synchronization and SSE events."""

import json
from unittest.mock import patch, MagicMock

from invoices.sync_daemon import push_sync_event, get_sse_stream, GDTSyncDaemon
from invoices.models import TaxpayerProfile, GDTSyncLog
from extensions import db

def test_push_sync_event_and_get_sse_stream():
    """Test the pub/sub event mechanism for Server-Sent Events."""
    import queue
    from invoices.sync_daemon import _sse_queue
    # Clear the global queue first
    while not _sse_queue.empty():
        try:
            _sse_queue.get_nowait()
        except queue.Empty:
            break

    # Push an event
    push_sync_event("test_event", {"message": "hello world"})
    
    # Read from stream
    stream_generator = get_sse_stream()
    
    # Get the first event from the generator
    data = next(stream_generator)
    
    assert data.startswith("data: ")
    assert data.endswith("\n\n")
    
    # Parse json content
    json_str = data[6:-2]
    parsed = json.loads(json_str)
    
    assert parsed["event"] == "test_event"
    assert parsed["data"]["message"] == "hello world"
    assert "timestamp" in parsed

def test_sync_daemon_cycle(app):
    """Test the daemon sync cycle successfully creates GDTSyncLog and pushes events."""
    import queue
    from invoices.sync_daemon import _sse_queue
    # Clear the global queue first
    while not _sse_queue.empty():
        try:
            _sse_queue.get_nowait()
        except queue.Empty:
            break

    with app.app_context():
        # Setup mock active taxpayer
        profile = TaxpayerProfile(
            mst="1234567890",
            company_name="CONG TY DEMO",
            gdt_username="demo_user",
            gdt_password_encrypted="demo",
            is_active=True,
            created_at="2026-01-01T00:00:00"
        )
        db.session.add(profile)
        db.session.commit()
        
        # Clear logs
        GDTSyncLog.query.delete()
        db.session.commit()
        
        # Instantiate and run cycle directly to avoid threading issues in test
        daemon = GDTSyncDaemon(app, interval_minutes=1)
        
        # Mock time.sleep to run instantly
        with patch('time.sleep', return_value=None):
            daemon._execute_sync_cycle()
        
        # Assert log was created
        logs = GDTSyncLog.query.all()
        assert len(logs) == 1
        assert logs[0].taxpayer_mst == "1234567890"
        assert logs[0].status == "success"
        assert logs[0].invoices_fetched == 1
        
        # Assert events were pushed to the queue
        # Try to retrieve events until empty or max
        events = []
        try:
            generator = get_sse_stream()
            # Fetch events generated by cycle
            for _ in range(4):
                import queue
                try:
                    from invoices.sync_daemon import _sse_queue
                    # non-blocking get for test
                    msg = _sse_queue.get(block=False)
                    events.append(json.loads(msg))
                except queue.Empty:
                    break
        except Exception:
            pass
            
        assert any(e["event"] == "sync_started" for e in events)
        assert any(e["event"] == "sync_progress" for e in events)
        assert any(e["event"] == "invoice_downloaded" for e in events)
        assert any(e["event"] == "sync_finished" for e in events)

def test_sse_sync_stream_endpoint(app, logged_in_client):
    """Verify the SSE endpoint requires authentication and returns the event stream."""
    
    push_sync_event("api_test", {"ok": True})
    
    response = logged_in_client.get("/api/sync/events")
    assert response.status_code == 200
    assert response.mimetype == "text/event-stream"
    # SSE responses might stream forever, so we can't fully consume in a simple test
    # But checking status and mimetype verifies the route is wired correctly.
